export OS_IDENTITY_API_VERSION=3
export OS_USER_DOMAIN_NAME=${DOMAIN_NAME}
export OS_USERNAME=admin
export OS_PROJECT_DOMAIN_NAME=${DOMAIN_NAME}
export OS_PROJECT_NAME=${PROJECT_NAME}
export OS_DOMAIN_NAME=${DOMAIN_NAME}
export OS_PASSWORD=${PASSWORD}
export OS_AUTH_URL=http://192.168.7.78:5000/v3
